---
# tasks file for con-pass-login

- name: Get {{ inventory_hostname }} Console password and login
  ios_command:
     commands: sh run | section line con 0 
  register: output  
  when: ansible_network_os is defined

- name: Check {{ inventory_hostname }} Console password and login
  assert:
    that: 
      - output.stdout[0] is search("password 7")
      - "' login' in output.stdout_lines[0]"
    fail_msg: "Console password and login configured incorrectly"
    success_msg: "Console password and login are configured correctly"
  register: end
  ignore_errors: yes

- import_role:
    name: save-output
  vars: 
    txt: "{{ end.msg }}"

- import_role:
    name: count-checks

- import_role:
    name: give-point
  when: end is succeeded
