---
# tasks file for ping-lab-devices

- name: Ping Lab Devices
  include_tasks: "{{ ping_os }}.yaml"
  register: output  
  when: ping_os is defined
  ignore_errors: yes

- import_role:
    name: save-output
  vars: 
    txt: "{{ output }}"
    
- import_role:
    name: count-checks

- import_role:
    name: give-point
  when: output is succeeded